language: ruby
cache: bundler
branches:
  only:
  - source
rvm:
- 2.5
install:
- bundle install
script:
- bundle exec rake publish
env:
  global:
    secure: "JnEMMmNk+RULfay721CSd+xvtYhfXm7w8sjZ4/DD0nzGt+cLQPrdbaepwvFU3KtztYJ6ShIFM+rf7SFm9UaaQiwhY5iij++IEe6z/pWru8/J42II8ILmPdIrmnOQCf4rrg5csESIfPffyyB7etqS9T8PUaFg+PlYM9zlXXyHNAY="
