# Site wide configuration

title: devth
description: there must be a better way
logo: logo_120.jpg
teaser: teaser_450_250.jpg
locale:
# url: http://devth.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/

markdown: kramdown

kramdown:
  input: GFM
  enable_coderay: true
  coderay_line_numbers: nil
  coderay_css: style

# markdown: KramdownPygments
# markdown: redcarpet
# markdown: Pypedown
# pypedown:
#   input: GFM
# highlighter: pygments

gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Trevor Hartman
  email: trevorhartman@gmail.com
  twitter: devth
  google:
    ad-client: 
    ad-slot: 
  bio: Automate or die
  avatar: bio-photo.png # 160x160 px image for author byline
disqus-shortname: devth


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

defaults:
  caption: 
