# Site wide configuration

title: devth
description: there must be a better way
logo: logo_120.jpg
teaser: teaser_450_250.jpg
locale: en_US
url: https://devth.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:year/:title


# markdown: KramdownPygments
# markdown: redcarpet

# markdown: Pypedown
# pypedown:
#   input: GFM
#   hard_wrap: false
#   line_width: 80
#   typogruby: false

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

# Site owner
owner:
  name: Trevor Hartman
  email: trevorhartman@gmail.com
  twitter: devth
  google:
    ad-client:
    ad-slot:
  bio: Automate or die
  avatar: bio-photo.png # 160x160 px image for author byline
disqus-shortname: devth

share: false

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

defaults:
  caption:
